include:
  - project: 'dti/agd/templates/ci-templates-javascript'
    ref: master
    file: 'react.yml'

variables:
  DOCKER_IMAGE_NAME: "normastouch-weg"
  AUTOMATIC_DEPLOYMENT_ON_QA: "true"
  K8S_APP_NAME: "normastouch-weg"
  K8S_DISABLE_HEALTHCHECK: "true"
  K8S_DISABLE_METRICS: "true"
  K8S_MEM_REQ: "500Mi"
  K8S_MEM_LIM: "1000Mi"
  K8S_REPLICAS: "2"
  K8S_APP_PORT: "15080"

deploy:qa:
  environment: qas
  variables:
    K8S_NAMESPACE: "qas-normastouch"
    REACT_APP_SUPABASE_PROJECT_ID: "ytlrgiklfnygbzrwhpdz"
    REACT_APP_SUPABASE_PUBLISHABLE_KEY: "seu_token_aqui"
    REACT_APP_SUPABASE_URL: "https://ytlrgiklfnygbzrwhpdz.supabase.co"
    GITLAB_TOKEN: ${QAS_GITLAB_TOKEN}

deploy:prd:
  environment: prd
  variables:
    K8S_NAMESPACE: "prd-normastouch"
    GITLAB_TOKEN: ${PRD_GITLAB_TOKEN}
