server {
    listen       15080;
    server_name  localhost;

    location / {
        root   /opt/app;
        try_files $uri /index.tsx;
        expires max;
        access_log off;
    }
}