apiVersion: v1
kind: ConfigMap
metadata:
  name: ${K8S_CONFIG_MAP_NAME}
  namespace: ${K8S_NAMESPACE}
data:
  REACT_APP_SUPABASE_PROJECT_ID: ${REACT_APP_SUPABASE_PROJECT_ID}
  REACT_APP_SUPABASE_PUBLISHABLE_KEY: ${REACT_APP_SUPABASE_PUBLISHABLE_KEY}
  REACT_APP_SUPABASE_URL: ${REACT_APP_SUPABASE_URL}
